on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - develop

name: "Build & Release Demoe flutter app" 

jobs:
  build_android:
    name: Build & Release Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '12.x'
          distribution: 'adopt'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.6'
          cache: true
          cache-key: flutter # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path  
      - run: flutter pub get
      - run: flutter build apk --debug --split-per-abi
      - run: flutter build appbundle
      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/apk/debug/* 

  build_ios:
    name: Build & Release iOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.6'
        cache: true
        cache-key: flutter # optional, change this to force refresh cache
        cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path  
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
    - name: Cache IPA
      id: cache-ipa
      uses: actions/cache@v3
      with:
        path: "build/ios/iphoneos/*"
        key: ipa

  push_ipa:
    name: Push IPA
    needs: [build_ios]
    runs-on: ubuntu-latest
    steps:
      - name: Restore cache
        id: cache-ipa
        uses: actions/cache@v3
        with:
          path: "build/ios/iphoneos/*"
          key: ipa
      - name: logs cache
        run: ls -all build/ios/iphoneos/
      
      
        